export const ADD_BUN = 'ADD_BUN';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const UPDATE_CONSTRUCTOR = 'UPDATE_CONSTRUCTOR';
export const DELETE_CONSTRUCTOR = 'DELETE_CONSTRUCTOR';
