export const SHOW_INGREDIENT_MODAL = 'SHOW_INGREDIENT_MODAL';
export const SHOW_ORDER_MODAL = 'SHOW_ORDER_MODAL';
export const HIDE_INGREDIENT_MODAL = 'HIDE_INGREDIENT_MODAL';
export const HIDE_ORDER_MODAL = 'HIDE_ORDER_MODAL';
